version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - server-network
    ports:
      - "5432:5432"
  backend:
    build: './backend'
    networks:
      - server-network
    ports:
      - "8080:8080"
    depends_on:
      - database
  frontend:
    build: './frontend'
    networks:
      - server-network
    ports:
      - "80:80"
    depends_on:
      - backend
networks:
  server-network:
    driver: bridge
