version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - server-network
    ports:
      - "5432:5432"
  backend:
    build:
      context: './backend'
      dockerfile: 'Dockerfile-dev'
    networks:
      - server-network
    ports:
      - "8080:8080"
    depends_on:
      - database
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=password psql -h \"database\" -U \"postgres\" -c '\\q'"]
      interval: 5s
      timeout: 3s
      retries: 3
  frontend:
    build: './frontend'
    networks:
      - server-network
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-q0", "http://backend/healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 3
networks:
  server-network:
    driver: bridge
