version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  backend:
    build: './backend'
    ports:
      - "8080:8080"
  frontend:
    build: './frontend'
    ports:
      - "80:80"
